name: Singularity build
on: workflow_dispatch

jobs:
  build-containers:
    runs-on: ubuntu-latest

    name: Build Singularity containers
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Install Singularity dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config

      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.9.0
          GOPATH: /tmp/go
      
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity-ce-${SINGULARITY_VERSION} && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install          

      - name: Check out code for the container build
        uses: actions/checkout@v2

      - name: Login to GitHub package registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io

      - name: Build and deploy Singularity containers
        run: |
         for recipe in $(find container_recipies -name "*.def"); do
            echo "Current recipe: $recipe"
            # Get basename of recipe (without <version>.def)
            basename=$(basename $recipe | sed -E 's/[0-9_]+\.def//g' | sed -E 's/.def//g')
            # Get version tag from recipe name
            tag=$(basename $recipe | sed -E 's/[A-Za-z]+_([0-9_]+)\.def/\1/g' | sed -E 's/_/./g' | sed -E 's/.def//g')
            if [ "$tag" == $(basename $recipe | sed -E 's/.def//g') ]; then
                tag=latest
            fi
            # Check if container exists
            base64token=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
            echo "Checking if container $basename:$tag already exists"
            if curl -s -H "Authorization: Bearer $base64token" https://ghcr.io/v2/${{ github.repository_owner }}/oncoliner_${basename}/tags/list | grep $tag; then
                echo "Container $basename:$tag already exists, skipping build"
                continue
            fi
            echo "Container $basename:$tag does not exist, building it"
            # Build container
            sudo -E singularity build $basename.sif $recipe
            # Push container and name by tag
            url="oras://ghcr.io/${{ github.repository_owner }}/oncoliner_${basename}:${tag}"
            echo "Pushing container to $url"
            singularity push $basename.sif $url
         done
